//! Boot assets — UKI assembly, ESP install, sysupdate transfers
//! (issue #57).

use std::path::{Path, PathBuf};

use miette::{IntoDiagnostic, WrapErr};

use super::*;
use crate::snap;
use crate::store::ResolvedSnap;

/// sysupdate.d file name prefix for shuttle-generated transfers — ordering
/// keeps root+verity ahead of the UKI within one sysupdate transaction.
pub(crate) const SYSUPDATE_DIR: &str = "usr/lib/sysupdate.d";

/// systemd-sysupdate trigger pair (ADR-0024 §2, #62). These are systemd's
/// own unit names — shuttle ships no update daemon (ADR-0011 §5).
pub(crate) const SYSUPDATE_SERVICE_NAME: &str = "systemd-sysupdate.service";
pub(crate) const SYSUPDATE_TIMER_NAME: &str = "systemd-sysupdate.timer";

/// Unit paths inside the staged rootfs.
///
/// `/etc/systemd/system/` — the administrator/override location — NOT
/// `/usr/lib/systemd/system/`, where the systemd package ships its own
/// `systemd-sysupdate.service`/`.timer`. Emitting to the vendor path would
/// collide with that file (same path, install-order-dependent winner),
/// whereas a unit in `/etc/systemd/system/` masks the vendor one by
/// systemd's documented precedence. This is the intended way to replace a
/// distro unit without patching systemd.
pub(crate) const SYSUPDATE_SERVICE_PATH: &str = "etc/systemd/system/systemd-sysupdate.service";
pub(crate) const SYSUPDATE_TIMER_PATH: &str = "etc/systemd/system/systemd-sysupdate.timer";

/// Emit the systemd-sysupdate transfer files into the staged rootfs
/// (`/usr/lib/sysupdate.d/`), pre-populate, so both slots carry them.
/// Called only for `disk.ab = true` images with a declared
/// `update_source`. Artifacts share one `@v` version: `{v}/root.img`,
/// `{v}/verity-hash.img`, `{v}/{name}_@v.efi` under the base URL.
pub(crate) fn write_sysupdate_transfers(
    root: &Path,
    image: &ImageDeclaration,
    disk: &DiskLayout,
) -> miette::Result<()> {
    let dir = root.join(SYSUPDATE_DIR);
    std::fs::create_dir_all(&dir).into_diagnostic()?;
    let root_mb = parse_size_mb(
        &disk
            .partitions
            .iter()
            .find(|p| p.mount == "/")
            .map(|p| p.size.clone())
            .unwrap_or_else(|| "1024".into()),
        1024,
    );
    let files = [
        ("50-root.transfer", root_transfer(&image.name, root_mb)),
        (
            "50-verity.transfer",
            hash_transfer(&image.name, verity_hash_partition_mb(disk)),
        ),
        ("60-uki.transfer", uki_transfer(&image.name)),
    ];
    for (name, content) in files {
        std::fs::write(dir.join(name), content)
            .into_diagnostic()
            .wrap_err_with(|| format!("writing sysupdate.d/{name}"))?;
    }
    eprintln!(
        "  ✓ sysupdate transfers: {SYSUPDATE_DIR}/50-root, 50-verity, 60-uki \
         (source: {})",
        image.update_source.as_deref().unwrap_or("")
    );
    Ok(())
}

/// Render `systemd-sysupdate.service` (ADR-0024 §2, #62).
///
/// `ExecStart=systemd-sysupdate update` runs systemd's own machinery
/// against the transfer definitions in [`SYSUPDATE_DIR`]. No
/// `--definitions=`/`--transfer-source=` flag is passed on purpose: the
/// systemd-sysupdate default definitions search path already reads
/// `/usr/lib/sysupdate.d/*.transfer` (`sysupdate.d(5)`, and the default is
/// `SYSUPDATE_DIR`), so restating it would be a second copy of the path
/// free to drift (`--transfer-source=` is unrelated — it resolves
/// `PathRelativeTo=explicit` sources, and it only exists from systemd 257).
///
/// The transfers carry `ProtectVersion=%A` themselves, so this unit needs
/// no image version: `update` with no VERSION installs the newest
/// available artifact and `%A` is resolved by systemd-sysupdate from the
/// running system's `/etc/os-release` `IMAGE_VERSION=`, not by the unit
/// (see [`ensure_os_release_image_version`], which guarantees that field).
pub(crate) fn sysupdate_service_content() -> String {
    "\
# Generated by shuttle — do not edit.
[Unit]
Description=shuttle: apply systemd-sysupdate A/B updates
# url-file transfers fetch over the network.
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
# A disposable-root update is a discrete job, not a state to hold.
RemainAfterExit=no
ExecStart=systemd-sysupdate update
"
    .to_string()
}

/// Render `systemd-sysupdate.timer` (ADR-0024 §2, #62).
///
/// Daily bounds device staleness to under a day without hammering the
/// update source. `RandomizedDelaySec` spreads a fleet that shipped (or
/// booted) together so every device does not fetch at the same instant,
/// and `Persistent=true` catches up a run missed while the device was
/// powered off.
pub(crate) fn sysupdate_timer_content() -> String {
    format!(
        "\
# Generated by shuttle — do not edit.
[Unit]
Description=shuttle: periodic systemd-sysupdate check

[Timer]
OnCalendar=daily
RandomizedDelaySec=1h
Persistent=true
Unit={SYSUPDATE_SERVICE_NAME}

[Install]
WantedBy=timers.target
"
    )
}

/// Emit the sysupdate trigger pair into the staged rootfs (ADR-0024 §2,
/// #62). Called by the same step-5c gate as
/// [`write_sysupdate_transfers`], so the units exist exactly when the
/// transfer definitions do.
///
/// The **timer** is enabled into `timers.target`. The **service** is not
/// enabled anywhere — it is pulled by the timer's `Unit=`. Enabling the
/// service into `multi-user.target` would run an update at every boot
/// instead of on the schedule the timer expresses.
///
/// The units consume the transfer definitions written to [`SYSUPDATE_DIR`]
/// through systemd-sysupdate's default definitions search path, which is
/// why the unit text names no path.
pub(crate) fn emit_sysupdate_units(root: &Path) -> miette::Result<()> {
    crate::emit::write_unit(
        root,
        Path::new(SYSUPDATE_SERVICE_PATH),
        &sysupdate_service_content(),
    )?;
    crate::emit::write_unit(
        root,
        Path::new(SYSUPDATE_TIMER_PATH),
        &sysupdate_timer_content(),
    )?;
    crate::emit::enable_unit(root, "timers.target", SYSUPDATE_TIMER_NAME)?;
    eprintln!("  ✓ {SYSUPDATE_TIMER_NAME} + {SYSUPDATE_SERVICE_NAME} emitted (ADR-0024 §2)");
    Ok(())
}

/// Ensure the staged rootfs's `/etc/os-release` carries `IMAGE_VERSION`.
///
/// The generated transfers carry `ProtectVersion=%A`; `%A` resolves to the
/// `IMAGE_VERSION=` field of the *running* system's `/etc/os-release` (NOT
/// `VERSION_ID=` — that is `%w`). The base snap's os-release does not set
/// `IMAGE_VERSION`, so without this the specifier expands to the empty
/// string and `ProtectVersion=` protects nothing — the exact inert-config
/// trap ADR-0024 exists to close.
///
/// The caller gates this with [`emits_sysupdate`]: an image with no update
/// source emits no transfers, so it must not have its os-release rewritten
/// either. The existing file is preserved (every key the base declared is
/// kept) with `IMAGE_VERSION` set or replaced; when no os-release exists
/// yet, a minimal deterministic one is written.
pub(crate) fn ensure_os_release_image_version(
    root: &Path,
    image: &ImageDeclaration,
) -> miette::Result<()> {
    let path = root.join("etc").join("os-release");
    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    let mut lines: Vec<String> = existing
        .lines()
        .filter(|l| !l.trim_start().starts_with("IMAGE_VERSION="))
        .map(str::to_string)
        .collect();
    if lines.is_empty() {
        lines.push("ID=shuttle".into());
        lines.push(format!("NAME=\"{}\"", image.name));
        lines.push(format!("VERSION_ID={}", image.version));
        lines.push(format!("PRETTY_NAME=\"shuttle {} {}\"", image.name, image.version));
    }
    lines.push(format!("IMAGE_VERSION={}", image.version));
    crate::emit::write_staged_file(root, Path::new("etc/os-release"), &(lines.join("\n") + "\n"))?;
    eprintln!(
        "  ✓ etc/os-release: IMAGE_VERSION={} (systemd-sysupdate %A / ProtectVersion)",
        image.version
    );
    Ok(())
}


/// Hash-partition size in MB for MinSize, mirroring the appended hash
/// partition for the layout's root.
pub(crate) fn verity_hash_partition_mb(disk: &DiskLayout) -> u64 {
    let root_mb = parse_size_mb(
        &disk
            .partitions
            .iter()
            .find(|p| p.mount == "/")
            .map(|p| p.size.clone())
            .unwrap_or_else(|| "1024".into()),
        1024,
    );
    verity_hash_partition_bytes(root_mb * 1024 * 1024).div_ceil(1024 * 1024)
}

pub(crate) fn transfer_header() -> String {
    // Requires systemd >= 256 (PathRelativeTo=boot needs >= 254; the
    // tries-suffix install flow is stable from 256 on).
    "# Generated by shuttle (ADR-0011 step d) — do not edit.\n\
     # systemd-sysupdate >= 256 recommended (PathRelativeTo=boot needs >= 254).\n"
        .to_string()
}

/// Root slot partition transfer: in-place update of the two root slots,
/// matched by the x86-64 root type GUID + the slot label scheme.
pub(crate) fn root_transfer(image_name: &str, min_size_mb: u64) -> String {
    format!(
        "{header}\n\
         [Transfer]\n\
         ProtectVersion=%A\n\
         \n\
         [Source]\n\
         Type=url-file\n\
         Path=%v/root.img\n\
         \n\
         [Target]\n\
         Type=partition\n\
         Path=in-places\n\
         MatchPartitionType={ROOT_TYPE_GUID_X86_64}\n\
         MatchPattern={pattern}\n\
         MinSize={min_size_mb}M\n\
         InstancesMax=2\n",
        header = transfer_header(),
        pattern = root_match_pattern(image_name),
    )
}

/// Verity-hash slot partition transfer — rewritten together with its root
/// slot (both artifacts carry the same @v; the roothash is build-time
/// embedded in the UKI cmdline and never modified at update time).
pub(crate) fn hash_transfer(image_name: &str, min_size_mb: u64) -> String {
    format!(
        "{header}\n\
         [Transfer]\n\
         ProtectVersion=%A\n\
         \n\
         [Source]\n\
         Type=url-file\n\
         Path=%v/verity-hash.img\n\
         \n\
         [Target]\n\
         Type=partition\n\
         Path=in-places\n\
         MatchPartitionType={VERITY_TYPE_GUID_X86_64}\n\
         MatchPattern={pattern}\n\
         MinSize={min_size_mb}M\n\
         InstancesMax=2\n",
        header = transfer_header(),
        pattern = hash_match_pattern(image_name),
    )
}

/// UKI regular-file transfer: installed under $BOOT/EFI/Linux with
/// boot-try counters added by sysupdate AT INSTALL (the factory UKI ships
/// without counters — always-good). systemd-boot's Automatic Boot
/// Assessment counts TriesLeft down and systemd-bless-boot.service clears
/// the counters on a good boot. The factory filename stays
/// `{name}_{version}.efi` (tries-compatible).
pub(crate) fn uki_transfer(image_name: &str) -> String {
    format!(
        "{header}\n\
         [Transfer]\n\
         ProtectVersion=%A\n\
         \n\
         [Source]\n\
         Type=url-file\n\
         Path=%v/{image_name}_@v.efi\n\
         \n\
         [Target]\n\
         Type=regular-file\n\
         Path=EFI/Linux\n\
         PathRelativeTo=boot\n\
         MatchPattern={image_name}_@v+@l-@d.efi {image_name}_@v+3-0.efi {image_name}_@v.efi\n\
         TriesLeft=3\n\
         TriesDone=0\n\
         InstancesMax=2\n",
        header = transfer_header(),
    )
}

/// Serialize and write the image manifest into the staged rootfs.
pub(crate) fn write_manifest(
    root: &Path,
    image: &ImageDeclaration,
    snaps: &[(String, ResolvedSnap)],
    arch: &str,
    boot: Option<&UkiFacts>,
) -> miette::Result<()> {
    let manifest = ImageManifest::from_resolved(image, snaps, arch, boot);
    let manifest_json = serde_json::to_string_pretty(&manifest)
        .map_err(|e| miette::miette!("failed to serialize manifest: {e}"))?;
    std::fs::write(root.join("image-manifest.json"), manifest_json)
        .into_diagnostic()
        .wrap_err("writing manifest")?;
    Ok(())
}

/// Copy the systemd-boot fallback binary onto the ESP (EFI/BOOT). When no
/// host systemd-boot EFI binary is found the ESP simply lacks the fallback
/// — the UKI + loader path does not depend on it.
pub(crate) fn populate_esp(runner: &dyn CommandRunner, efi_boot: &Path) -> miette::Result<()> {
    std::fs::create_dir_all(efi_boot).into_diagnostic()?;
    if efi_boot.join("BOOTX64.EFI").exists() {
        return Ok(());
    }
    // systemd-boot fallback binary: exact name first (a `*.efi` glob would
    // also match linuxx64.efi.stub — the WRONG binary for BOOTX64.EFI),
    // across the standard FHS roots and the NixOS system profile.
    const BOOT_ROOTS: [&str; 3] = [
        "/usr/lib/systemd/boot",
        "/usr/local/lib/systemd/boot",
        "/run/current-system/sw/lib/systemd/boot",
    ];
    let mut src: Option<PathBuf> = None;
    for root in BOOT_ROOTS {
        let root = Path::new(root);
        let exact = root.join("efi/systemd-bootx64.efi");
        if exact.is_file() {
            src = Some(exact);
            break;
        }
        let argv = vec![
            "find".to_string(),
            root.to_string_lossy().into_owned(),
            "-name".to_string(),
            "systemd-boot*.efi".to_string(),
        ];
        if let Ok(out) = runner.run(&argv) {
            let stdout = String::from_utf8_lossy(&out.stdout).into_owned();
            let hit = stdout.lines().next().unwrap_or("");
            if !hit.trim().is_empty() {
                src = Some(PathBuf::from(hit.trim()));
                break;
            }
        }
    }
    if let Some(src) = src {
        let _ = std::fs::copy(&src, efi_boot.join("BOOTX64.EFI"));
        let _ = std::fs::copy(&src, efi_boot.join("systemd-bootx64.efi"));
    }
    Ok(())
}

/// Install the UKI and the systemd-boot loader config onto the mounted
/// ESP. Type-2 UKIs in EFI/Linux/*.efi are auto-discovered by systemd-boot
/// — no per-entry loader file is needed.
pub(crate) fn install_uki(
    image: &ImageDeclaration,
    esp_mount: &Path,
    uki: Option<&UkiFacts>,
    uki_stage: &Path,
) -> miette::Result<()> {
    let Some(facts) = uki else {
        return Ok(());
    };
    let efi_linux = esp_mount.join("EFI").join("Linux");
    std::fs::create_dir_all(&efi_linux).into_diagnostic()?;
    std::fs::copy(uki_stage, efi_linux.join(&facts.uki_filename))
        .into_diagnostic()
        .wrap_err_with(|| format!("installing {}", facts.uki_filename))?;
    let loader_dir = esp_mount.join("loader");
    std::fs::create_dir_all(&loader_dir).into_diagnostic()?;
    std::fs::write(loader_dir.join("loader.conf"), loader_conf(image)).into_diagnostic()?;
    eprintln!(
        "  ✓ UKI installed: EFI/Linux/{} (cmdline: {})",
        facts.uki_filename, facts.cmdline
    );
    Ok(())
}

// ── UKI assembly (ADR-0011 step (a)) ──

/// A kernel snap's boot assets, located per the payload convention in
/// [`locate_kernel_payload`].
#[derive(Debug)]
pub(crate) struct KernelPayload {
    pub(crate) kernel: PathBuf,
    pub(crate) initrd: PathBuf,
    pub(crate) version: String,
}

/// Boot facts captured during UKI assembly (ADR-0011 step (a)) and threaded
/// into the build manifest — the image records what will actually boot,
/// not just what was packed.
pub(crate) struct UkiFacts {
    pub(crate) kernel_version: String,
    pub(crate) cmdline: String,
    pub(crate) uki_filename: String,
    pub(crate) esp_partuuid: Option<String>,
    /// dm-verity root hash embedded in the cmdline (ADR-0011 step (c));
    /// None for images that boot without verity.
    pub(crate) roothash: Option<String>,
}

/// GPT PARTUUID emitted when the real root PARTUUID could not be resolved.
/// Documented placeholder strategy: the nil GUID makes the failure loud —
/// nothing can mount a partition that does not exist, so the image never
/// silently boots from the wrong volume. In practice the real PARTUUID is
/// captured: parted assigns GPT GUIDs at mkpart time and `sfdisk -J` reads
/// them back from the finished table before the UKI is built.
pub(crate) const NIL_PARTUUID: &str = "00000000-0000-0000-0000-000000000000";

/// Standard locations of the systemd sd-stub for x86_64 — all under the
/// sandbox bind roots ([`crate::snap::SANDBOX_RO_ROOTS`]).
pub(crate) const EFI_STUB_CANDIDATES: [&str; 3] = [
    "/usr/lib/systemd/boot/efi/linuxx64.efi.stub",
    "/usr/local/lib/systemd/boot/efi/linuxx64.efi.stub",
    "/run/current-system/sw/lib/systemd/boot/efi/linuxx64.efi.stub",
];

/// Kernel-snap payload convention (ADR-0011 step (a)) — defined explicitly
/// because no convention existed: pkgs/*-kernel.lua snaps are source-type
/// with no packed kernel. After the snap is extracted, boot assets are read
/// from the payload in this fixed order, with the version taken from the
/// merged rootfs module tree (`lib/modules/<version>` — the only kernel
/// payload path this repo already merges):
///
///   kernel: boot/vmlinuz-<ver> → boot/vmlinuz → vmlinuz-<ver> → vmlinuz
///   initrd: boot/initrd.img-<ver> → boot/initrd.img → initrd.img → initrd
///
/// Raw kernel binaries only: a snapd-style `kernel.img` squashfs payload is
/// not unpacked (that is gadget-stage behavior, out of scope).
pub(crate) fn locate_kernel_payload(
    kernel_dir: &Path,
    root: &Path,
) -> miette::Result<KernelPayload> {
    let version = discover_kernel_version(root)?;
    let kernel = first_existing([
        kernel_dir.join("boot").join(format!("vmlinuz-{version}")),
        kernel_dir.join("boot").join("vmlinuz"),
        kernel_dir.join(format!("vmlinuz-{version}")),
        kernel_dir.join("vmlinuz"),
    ])
    .ok_or_else(|| {
        miette::miette!(
            "payload has no kernel image (searched boot/vmlinuz-{version}, boot/vmlinuz, \
             vmlinuz-{version}, vmlinuz)"
        )
    })?;
    let initrd = first_existing([
        kernel_dir
            .join("boot")
            .join(format!("initrd.img-{version}")),
        kernel_dir.join("boot").join("initrd.img"),
        kernel_dir.join("initrd.img"),
        kernel_dir.join("initrd"),
    ])
    .ok_or_else(|| {
        miette::miette!(
            "payload has no initrd (searched boot/initrd.img-{version}, boot/initrd.img, \
             initrd.img, initrd)"
        )
    })?;
    Ok(KernelPayload {
        kernel,
        initrd,
        version,
    })
}

/// Build-time hard gate (ADR-0024 §1): the resolved kernel's initrd must
/// carry every boot-chain module its config builds as a module
/// (`virtio_blk`, `virtio_pci`, `dm_mod`, `dm-verity`, `ext4` on the
/// audited kernels). A kernel whose initrd cannot see its own disk is a
/// brick, so this FAILS CLOSED — an unavailable config, an unreadable or
/// unrecognized initrd, and a missing module are all hard errors naming
/// the exact cause. The required set is derived from the kernel config
/// ([`doctor::inspect_initrd_modules`]), never hardcoded.
pub(crate) fn audit_initrd_modules(
    runner: &dyn CommandRunner,
    payload_dir: &Path,
    payload: &KernelPayload,
) -> miette::Result<()> {
    use crate::doctor::InitrdModuleAudit;
    match doctor::inspect_initrd_modules(runner, payload_dir, &payload.version, &payload.initrd) {
        InitrdModuleAudit::Satisfied(modules) if modules.is_empty() => {
            eprintln!(
                "  ✓ initrd module audit: kernel {} builds the boot chain in — no \
                 initrd modules required",
                payload.version
            );
            Ok(())
        }
        InitrdModuleAudit::Satisfied(modules) => {
            eprintln!(
                "  ✓ initrd module audit: kernel {} initrd carries {}",
                payload.version,
                modules.join(", ")
            );
            Ok(())
        }
        InitrdModuleAudit::Missing { config, missing } => Err(miette::miette!(
            "kernel {} initrd is missing boot-chain module(s): {} (required by {}); \
             the kernel cannot see its own disk at boot — refusing to build a disk \
             image that cannot boot (ADR-0024 §1)",
            payload.version,
            missing.join(", "),
            config.display()
        )),
        InitrdModuleAudit::NoConfig => Err(miette::miette!(
            "no kernel config found for {} under {} — cannot derive the required \
             boot-chain modules, and a kernel whose initrd cannot be verified must \
             not ship; refusing to build a disk image that cannot boot (ADR-0024 §1)",
            payload.version,
            payload_dir.display()
        )),
        InitrdModuleAudit::Unreadable(reason) => Err(miette::miette!(
            "kernel {} initrd {} could not be read: {reason}; refusing to build a \
             disk image that cannot boot (ADR-0024 §1)",
            payload.version,
            payload.initrd.display()
        )),
    }
}

/// First path in `candidates` that exists as a file.
pub(crate) fn first_existing(candidates: impl IntoIterator<Item = PathBuf>) -> Option<PathBuf> {
    candidates.into_iter().find(|p| p.is_file())
}

/// Kernel version from the merged rootfs module tree: the single directory
/// under `lib/modules/`. Ambiguous or absent trees fail closed.
pub(crate) fn discover_kernel_version(root: &Path) -> miette::Result<String> {
    let modules_dir = root.join("lib").join("modules");
    let mut versions: Vec<String> = std::fs::read_dir(&modules_dir)
        .into_diagnostic()
        .wrap_err_with(|| format!("reading {}", modules_dir.display()))?
        .flatten()
        .filter(|e| e.path().is_dir())
        .filter_map(|e| e.file_name().to_str().map(str::to_string))
        .collect();
    versions.sort();
    match versions.as_slice() {
        [one] => Ok(one.clone()),
        [] => Err(miette::miette!(
            "no kernel module tree (lib/modules/<version>) in the merged rootfs — \
             the kernel snap carries no recognizable version"
        )),
        many => Err(miette::miette!(
            "ambiguous kernel module trees {many:?} in the merged rootfs — a kernel \
             snap must carry exactly one lib/modules/<version>"
        )),
    }
}

/// Resolve ukify with the same bind-aware PATH resolution the sandbox
/// toolchain uses ([`crate::snap::resolve_in_path`]). ukify runs host-side
/// — like mksquashfs/dd — so the full host PATH is the right search set;
/// the shared helper keeps one resolution behavior across shuttle.
pub(crate) fn find_ukify() -> Option<PathBuf> {
    snap::resolve_in_path("ukify", &snap::path_entries())
}

/// Locate the systemd sd-stub the UKI is built on.
pub(crate) fn find_efi_stub() -> Option<PathBuf> {
    for candidate in EFI_STUB_CANDIDATES {
        let path = Path::new(candidate);
        if path.is_file() {
            return Some(path.to_path_buf());
        }
    }
    None
}

/// Filename of the UKI on the ESP (systemd-boot auto-discovers Type-2 UKIs
/// in EFI/Linux/, and the loader.conf default pattern keys off this name).
pub(crate) fn uki_filename(image: &ImageDeclaration) -> String {
    format!("{}_{}.efi", image.name, image.version)
}

/// Compose the UKI kernel command line from parts — never one opaque
/// string. A UKI's `.cmdline` section is immutable once built, and dm-verity
/// boot (ADR-0011 step (c)) appends `roothash=` plus the explicit verity
/// device arguments ([`verity_trailing`]) and Secure Boot will later sign
/// the result, so composition stays programmatic: declared kernel params
/// first (user intent), then the `root=` argument derived from the target
/// root partition, then the trailing verity args (appended last).
pub(crate) fn compose_cmdline(
    params: &[String],
    root_partuuid: Option<&str>,
    trailing: &[String],
) -> String {
    let mut args: Vec<String> = params.to_vec();
    args.push(match root_partuuid {
        Some(uuid) => format!("root=PARTUUID={uuid}"),
        None => format!("root=PARTUUID={NIL_PARTUUID}"),
    });
    args.extend(trailing.iter().cloned());
    args.join(" ")
}

/// Deterministic os-release for the UKI: no timestamps, no host facts —
/// the same definition always yields byte-identical boot assets.
///
/// `IMAGE_VERSION` is set deliberately: systemd-sysupdate's `%A` transfer
/// specifier resolves to the `IMAGE_VERSION=` field (NOT `VERSION_ID=` —
/// that is `%w`), and the generated transfers carry
/// `ProtectVersion=%A` (ADR-0011 step (d)). Without this field `%A`
/// expands to the empty string and `ProtectVersion=` protects nothing.
pub(crate) fn write_uki_os_release(
    stage_dir: &Path,
    image: &ImageDeclaration,
) -> miette::Result<PathBuf> {
    let path = stage_dir.join("os-release");
    std::fs::write(
        &path,
        format!(
            "ID=shuttle\nNAME=\"{name}\"\nVERSION_ID={version}\nIMAGE_VERSION={version}\nPRETTY_NAME=\"shuttle {name} {version}\"\n",
            name = image.name,
            version = image.version,
        ),
    )
    .into_diagnostic()?;
    Ok(path)
}

/// Build one UKI with the real `ukify` CLI. `ukify` and `stub` are
/// injected so the fail-closed behavior is testable on hosts without
/// systemd's tools; [`build_uki`] resolves them from the host.
#[allow(clippy::too_many_arguments)]
pub(crate) fn build_uki_with(
    runner: &dyn CommandRunner,
    ukify: Option<&Path>,
    stub: Option<&Path>,
    kernel: &Path,
    initrd: &Path,
    cmdline: &str,
    os_release: &Path,
    output: &Path,
) -> miette::Result<()> {
    let Some(ukify) = ukify else {
        return Err(miette::miette!(
            "ukify not found on PATH — a kernel disk image cannot boot without a UKI, \
             so refusing to produce an unbootable image. Run 'shuttle doctor' and \
             install ukify (systemd >= 254; e.g. apt install systemd-ukify or add \
             systemd to devbox.json packages)"
        ));
    };
    let Some(stub) = stub else {
        return Err(miette::miette!(
            "systemd sd-stub (linuxx64.efi.stub) not found — the UKI cannot be assembled \
             without it. Run 'shuttle doctor'; checked locations: {}",
            EFI_STUB_CANDIDATES.join(", ")
        ));
    };
    let argv = vec![
        ukify.to_string_lossy().into_owned(),
        "build".to_string(),
        format!("--linux={}", kernel.display()),
        format!("--initrd={}", initrd.display()),
        format!("--cmdline={cmdline}"),
        format!("--os-release=@{}", os_release.display()),
        format!("--stub={}", stub.display()),
        format!("--output={}", output.display()),
    ];
    let out = runner
        .run(&argv)
        .map_err(|e| miette::miette!("failed to run ukify: {e}"))?;
    if out.code != 0 || !output.is_file() {
        return Err(miette::miette!(
            "ukify failed to build the UKI — the disk image would not boot; \
             refusing to emit it"
        ));
    }
    Ok(())
}

/// Build the UKI with host-resolved ukify and sd-stub (fail-closed when
/// either is absent).
pub(crate) fn build_uki(
    runner: &dyn CommandRunner,
    kernel: &Path,
    initrd: &Path,
    cmdline: &str,
    os_release: &Path,
    output: &Path,
) -> miette::Result<()> {
    build_uki_with(
        runner,
        find_ukify().as_deref(),
        find_efi_stub().as_deref(),
        kernel,
        initrd,
        cmdline,
        os_release,
        output,
    )
}

/// Compose the cmdline, build the UKI into `stage_dir`, and capture the
/// boot facts for the manifest. The facts are `None` only for kernel-free
/// images (nothing to boot, no UKI needed); the staged UKI path is empty
/// then and never used. `verity` carries the ADR-0011 step (c) format-time
/// roothash — Some exactly when the build verity-formatted the root
/// partition (kernel images).
pub(crate) fn assemble_uki(
    runner: &dyn CommandRunner,
    image: &ImageDeclaration,
    payload: Option<&KernelPayload>,
    extents: &[PartitionExtent],
    layout: &DiskLayout,
    stage_dir: &Path,
    verity: Option<&VerityBootArgs>,
) -> miette::Result<(Option<UkiFacts>, PathBuf)> {
    let Some(entry) = image.kernel.as_ref() else {
        return Ok((None, PathBuf::new()));
    };
    let Some(payload) = payload else {
        return Err(miette::miette!(
            "kernel snap '{}' declared but its boot payload was not extracted — \
             refusing to build a disk image that cannot boot",
            entry.snap.name
        ));
    };
    let root_idx = root_partition_index(layout)?;

    // GPT PARTUUIDs exist from parted mkpart time and are read back from
    // the finished table (`sfdisk -J`) before anything is formatted. ESP
    // is partition 1 (extent index 0).
    let root_partuuid = extents[root_idx].partuuid.clone();
    let esp_partuuid = extents[0].partuuid.clone();
    if root_partuuid.is_none() {
        eprintln!(
            "  ⚠ root PARTUUID unresolvable — cmdline carries the documented \
             nil-GUID placeholder (see compose_cmdline)"
        );
    }

    let trailing: Vec<String> = verity
        .map(|v| {
            verity_trailing(
                &v.roothash,
                root_partuuid.as_deref(),
                v.hash_partuuid.as_deref(),
            )
        })
        .unwrap_or_default();
    let cmdline = compose_cmdline(&entry.params, root_partuuid.as_deref(), &trailing);
    let filename = uki_filename(image);
    let uki_stage = stage_dir.join(&filename);
    let os_release = write_uki_os_release(stage_dir, image)?;
    build_uki(
        runner,
        &payload.kernel,
        &payload.initrd,
        &cmdline,
        &os_release,
        &uki_stage,
    )?;
    eprintln!("  ✓ UKI built: {filename}");

    Ok((
        Some(UkiFacts {
            kernel_version: payload.version.clone(),
            cmdline,
            uki_filename: filename,
            esp_partuuid,
            roothash: verity.map(|v| v.roothash.clone()),
        }),
        uki_stage,
    ))
}

/// systemd-boot loader configuration at the ESP root. Type-2 UKIs in
/// EFI/Linux/*.efi are auto-discovered — no per-entry loader file needed —
/// but the timeout and default pattern live here.
pub(crate) fn loader_conf(image: &ImageDeclaration) -> String {
    let timeout = image.bootloader.as_ref().map(|b| b.timeout).unwrap_or(3);
    // `default` is a glob: any UKI built for this image name matches,
    // regardless of version.
    format!(
        "# Generated by shuttle — do not edit.\ntimeout {timeout}\ndefault {}_*\n",
        image.name
    )
}
