//! Declared partition mounts → `etc/fstab` (ADR-0024 §3 support).
//!
//! The DSL lets an image declare a `mount` on every partition, but before
//! this module only the root (identified by PARTUUID on the UKI cmdline)
//! and the persistent state partition (`/var/lib`, ADR-0023) were ever
//! materialized. A declared ESP mounted at `/boot` or `/efi` therefore
//! never reached `/etc/fstab`: `systemd-bless-boot good` probes only
//! `/efi`, `/boot`, `/boot/efi` for an ESP and fails `-ENOENT` when the
//! ESP is not mounted there, breaking the ADR-0024 §3 boot-assessment
//! chain.
//!
//! This module owns `etc/fstab` end to end: the declared-mount lines
//! (identified by GPT PARTLABEL, which survives A/B flips — the fstab is
//! emitted BEFORE `create_partitions`, so no PARTUUID exists yet) and the
//! existing state lines from [`super::state_fstab_lines`]. There is exactly
//! ONE header and ONE renderer of the file.

use std::path::Path;

use super::*;

/// One declared partition mount, as it will be rendered into `etc/fstab`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct DeclaredMount {
    /// GPT PARTLABEL: the declared partition `name` (`mkpart_name`).
    pub(crate) partlabel: String,
    /// The declared mount point, honored verbatim.
    pub(crate) mount: String,
    /// The declared mount options, appended after `defaults,nofail`.
    pub(crate) options: Vec<String>,
    /// Whether this partition is the ESP (partition index 0 with
    /// `fs == "vfat"` — how `populate_side_partition` identifies it).
    pub(crate) is_esp: bool,
}

/// The declared non-root, non-state mounts, in declaration order.
///
/// Skips:
/// - the root (`mount == "/"`) — the UKI cmdline already carries
///   `root=PARTUUID=`;
/// - verity-hash partitions (`mount.is_empty()`);
/// - the persistent state partition — rendered by the state lines.
pub(crate) fn declared_mounts(layout: &DiskLayout) -> Vec<DeclaredMount> {
    layout
        .partitions
        .iter()
        .enumerate()
        .filter(|(_, p)| p.mount != "/" && !p.mount.is_empty() && !super::is_state_partition(p))
        .map(|(i, p)| DeclaredMount {
            partlabel: p.name.clone(),
            mount: p.mount.clone(),
            options: p.options.clone(),
            is_esp: i == 0 && p.fs == "vfat",
        })
        .collect()
}

/// The declared ESP mount point, when the layout declares one. The ESP is
/// partition index 0 with `fs == "vfat"` (`populate_side_partition`),
/// which is the mount whose `RequiresMountsFor=` the ESP-writing
/// consumers carry.
pub(crate) fn esp_mount_point(layout: &DiskLayout) -> Option<&str> {
    layout
        .partitions
        .first()
        .filter(|p| p.fs == "vfat" && p.mount != "/")
        .map(|p| p.mount.as_str())
}

/// Fail-closed validation: a vfat partition declaring a `/boot`-ish mount
/// that systemd cannot discover.
///
/// systemd's ESP probe (`systemd-bless-boot`, `bootctl`) only looks at
/// `/efi`, `/boot`, and `/boot/efi`. A vfat partition mounted anywhere
/// under `/boot` that is not exactly one of those would be formatted and
/// populated but never found at boot.
fn validate_esp_mount(m: &DeclaredMount) -> miette::Result<()> {
    if m.is_esp && m.mount.starts_with("/boot") && m.mount != "/boot" && m.mount != "/boot/efi" {
        return Err(miette::miette!(
            "partition '{}' is an ESP (vfat) mounted at '{}' — systemd can only \
             discover an ESP at /efi, /boot, or /boot/efi. Declare one of those \
             mount points so the boot-assessment chain (ADR-0024 §3) can find it",
            m.partlabel,
            m.mount
        ));
    }
    Ok(())
}

/// `etc/fstab` content: the declared-mount lines, then the state lines
/// when the split is active. One header, one file.
pub(crate) fn fstab_content(mounts: &[DeclaredMount], state: Option<&StateSplit>) -> String {
    let mut out = String::from(
        "# Generated by shuttle — do not edit.\n\
         # Declared partition mounts: survive A/B flips, identified by GPT PARTLABEL.\n",
    );
    for m in mounts {
        let mut opts = String::from("defaults,nofail");
        for opt in &m.options {
            opts.push(',');
            opts.push_str(opt);
        }
        out.push_str(&format!(
            "PARTLABEL={} {} auto {}\n",
            m.partlabel, m.mount, opts
        ));
    }
    if let Some(split) = state {
        for line in super::state_fstab_lines(split) {
            out.push_str(&line);
            out.push('\n');
        }
    }
    out
}

/// Emit `etc/fstab` (and any tmpfiles needed for a `/var` shadowed mount)
/// into the staged rootfs, plus the build-time mount-point directories.
///
/// Written BEFORE root populate + dm-verity — the same write-before-hash
/// constraint as the manifest and app runtime — so `/etc/fstab` lands
/// inside the hashed tree. The PARTUUID does not exist yet at this point
/// (partitions are created later), which is exactly why identification is
/// PARTLABEL.
pub(crate) fn emit_mounts(
    root: &Path,
    mounts: &[DeclaredMount],
    state: Option<&StateSplit>,
) -> miette::Result<()> {
    for m in mounts {
        validate_esp_mount(m)?;
    }

    let var_tmpfiles = create_mount_points(root, mounts, state.is_some())?;

    crate::emit::write_staged_file(
        root,
        Path::new(super::state::FSTAB_PATH),
        &fstab_content(mounts, state),
    )?;

    if let Some(split) = state {
        emit_state_tmpfiles(root, &var_tmpfiles, split)?;
    }

    if !mounts.is_empty() {
        eprintln!(
            "  ✓ etc/fstab: {} declared mount(s) by PARTLABEL, {} state line(s)",
            mounts.len(),
            usize::from(state.is_some()) * 2
        );
    }
    Ok(())
}

/// Materialize each declared mount point in the staged rootfs, returning
/// the mounts that must instead be created at boot by tmpfiles (declared
/// under `/var` while the `tmpfs /var` line is emitted).
fn create_mount_points(
    root: &Path,
    mounts: &[DeclaredMount],
    var_tmpfs: bool,
) -> miette::Result<Vec<String>> {
    let mut var_tmpfiles: Vec<String> = Vec::new();
    for m in mounts {
        if var_tmpfs && m.mount.starts_with("/var/") {
            var_tmpfiles.push(m.mount.clone());
        } else {
            create_mount_point(root, &m.mount)?;
        }
    }
    Ok(var_tmpfiles)
}

/// Write the state tmpfiles and the volatile-`/var` tmpfiles — the latter
/// additionally creating any declared `/var` mount point shadowed by the
/// tmpfs.
fn emit_state_tmpfiles(
    root: &Path,
    var_tmpfiles: &[String],
    split: &StateSplit,
) -> miette::Result<()> {
    crate::emit::write_staged_file(
        root,
        Path::new(super::state::STATE_TMPFILES_PATH),
        &super::state::state_tmpfiles_content(),
    )?;
    crate::emit::write_staged_file(
        root,
        Path::new(super::state::VAR_TMPFILES_PATH),
        &super::state::var_tmpfiles_content_with(var_tmpfiles),
    )?;
    eprintln!(
        "  ✓ /var split: state on PARTLABEL={} → {}, /var tmpfs + tmpfiles",
        split.partlabel,
        super::state::STATE_MOUNT
    );
    Ok(())
}

/// Create a mount-point directory inside the staged rootfs (mode 0755, via
/// the process umask). The root is dm-verity read-only at boot and
/// systemd's `mount_enter_mounting` only WARNS when the mount point cannot
/// be created, so a missing directory must be materialized at build time.
fn create_mount_point(root: &Path, mount: &str) -> miette::Result<()> {
    let rel = mount.trim_start_matches('/');
    if rel.is_empty() {
        return Ok(());
    }
    let dir = root.join(rel);
    std::fs::create_dir_all(&dir)
        .into_diagnostic()
        .wrap_err_with(|| format!("creating mount point {}", dir.display()))?;
    // Explicit mode: the process umask must not decide the on-disk mode of
    // a mount point the boot needs to traverse.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&dir, std::fs::Permissions::from_mode(0o755))
            .into_diagnostic()
            .wrap_err_with(|| format!("setting mode on {}", dir.display()))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn part(name: &str, fs: &str, mount: &str, role: &str) -> Partition {
        Partition {
            name: name.into(),
            size: "512M".into(),
            fs: fs.into(),
            mount: mount.into(),
            options: vec![],
            role: role.into(),
        }
    }

    fn disk_layout(parts: Vec<Partition>) -> DiskLayout {
        DiskLayout {
            label: "gpt".into(),
            partitions: parts,
            swap: None,
            ab: false,
        }
    }

    fn root() -> Partition {
        part("root", "ext4", "/", "")
    }

    #[test]
    fn declared_mounts_filters_root_empty_and_state_and_keeps_order() {
        let layout = disk_layout(vec![
            part("esp", "vfat", "/boot", ""),
            root(),
            part("hash", "ext2", "", ""),
            part("state", "ext4", "/var/lib", ROLE_STATE),
            part("data", "ext4", "/data", ""),
        ]);
        let mounts = declared_mounts(&layout);
        let points: Vec<&str> = mounts.iter().map(|m| m.mount.as_str()).collect();
        assert_eq!(points, vec!["/boot", "/data"], "declaration order kept");
        assert_eq!(mounts[0].partlabel, "esp");
        assert!(mounts[0].is_esp, "index 0 vfat is the ESP");
        assert!(!mounts[1].is_esp);
    }

    #[test]
    fn esp_mount_point_is_index_zero_vfat() {
        let layout = disk_layout(vec![
            part("esp", "vfat", "/boot", ""),
            root(),
            part("data", "ext4", "/data", ""),
        ]);
        assert_eq!(esp_mount_point(&layout), Some("/boot"));
        assert_eq!(esp_mount_point(&disk_layout(vec![root()])), None);
    }

    #[test]
    fn fstab_declared_mounts_golden() {
        let mounts = declared_mounts(&disk_layout(vec![
            part("esp", "vfat", "/boot", ""),
            root(),
            part("data", "ext4", "/data", ""),
        ]));
        let split = StateSplit {
            partlabel: "state".into(),
            var_submount_partlabel: String::new(),
        };
        let fstab = fstab_content(&mounts, Some(&split));
        let expected = "\
# Generated by shuttle — do not edit.
# Declared partition mounts: survive A/B flips, identified by GPT PARTLABEL.
PARTLABEL=esp /boot auto defaults,nofail
PARTLABEL=data /data auto defaults,nofail
# The persistent state partition (ADR-0023): survives A/B flips, never verity-hashed.
PARTLABEL=state /var/lib auto defaults,nofail
# /var is volatile: the skeleton is tmpfs, scratch state is tmpfiles (ADR-0023 §2).
tmpfs /var tmpfs mode=0755,nosuid,nodev
";
        assert_eq!(fstab, expected);
    }

    #[test]
    fn fstab_appends_declared_options_after_defaults_nofail() {
        let mut data = part("data", "ext4", "/data", "");
        data.options = vec!["noatime".into(), "discard".into()];
        let mounts = declared_mounts(&disk_layout(vec![root(), data]));
        let fstab = fstab_content(&mounts, None);
        assert!(
            fstab.contains("PARTLABEL=data /data auto defaults,nofail,noatime,discard\n"),
            "declared options appended: {fstab}"
        );
        assert_eq!(
            fstab.matches("# Generated by shuttle").count(),
            1,
            "exactly one header: {fstab}"
        );
    }

    #[test]
    fn fstab_without_state_emits_only_declared_lines() {
        let mounts = declared_mounts(&disk_layout(vec![part("esp", "vfat", "/boot", ""), root()]));
        let fstab = fstab_content(&mounts, None);
        assert_eq!(
            fstab,
            "# Generated by shuttle — do not edit.\n\
             # Declared partition mounts: survive A/B flips, identified by GPT PARTLABEL.\n\
             PARTLABEL=esp /boot auto defaults,nofail\n"
        );
    }

    #[test]
    fn esp_validation_rejects_an_undiscoverable_boot_mount() {
        let mounts = declared_mounts(&disk_layout(vec![
            part("esp", "vfat", "/bootloader", ""),
            root(),
        ]));
        let rootdir = tempfile::tempdir().unwrap();
        let err = emit_mounts(rootdir.path(), &mounts, None)
            .unwrap_err()
            .to_string();
        assert!(
            err.contains("/bootloader") && err.contains("/efi, /boot, or /boot/efi"),
            "fail-closed ESP path error: {err}"
        );
    }

    #[test]
    fn emit_mounts_creates_mount_point_directories() {
        let rootdir = tempfile::tempdir().unwrap();
        let mounts = declared_mounts(&disk_layout(vec![
            part("esp", "vfat", "/boot", ""),
            root(),
            part("data", "ext4", "/data", ""),
        ]));
        emit_mounts(rootdir.path(), &mounts, None).unwrap();
        assert!(rootdir.path().join("boot").is_dir());
        assert!(rootdir.path().join("data").is_dir());
        assert!(rootdir.path().join("etc/fstab").is_file());
    }

    #[test]
    fn emit_mounts_under_var_goes_to_tmpfiles_when_the_split_is_on() {
        let rootdir = tempfile::tempdir().unwrap();
        let mounts = declared_mounts(&disk_layout(vec![
            part("esp", "vfat", "/boot", ""),
            root(),
            part("docker", "ext4", "/var/lib/docker", ""),
        ]));
        let split = StateSplit {
            partlabel: "state".into(),
            var_submount_partlabel: "docker".into(),
        };
        emit_mounts(rootdir.path(), &mounts, Some(&split)).unwrap();
        // Shadowed by the tmpfs: not a build-time mkdir, but a tmpfiles line.
        assert!(
            !rootdir.path().join("var/lib/docker").exists(),
            "build-time mkdir would be shadowed by tmpfs /var"
        );
        let var =
            std::fs::read_to_string(rootdir.path().join(super::super::state::VAR_TMPFILES_PATH))
                .unwrap();
        assert!(
            var.contains("d /var/lib/docker 0755 root root -"),
            "tmpfiles creates the shadowed mount point: {var}"
        );
    }

    #[test]
    fn emit_mounts_under_var_uses_a_build_time_mkdir_without_the_tmpfs() {
        let rootdir = tempfile::tempdir().unwrap();
        let mounts = declared_mounts(&disk_layout(vec![
            part("esp", "vfat", "/boot", ""),
            root(),
            part("docker", "ext4", "/var/lib/docker", ""),
        ]));
        emit_mounts(rootdir.path(), &mounts, None).unwrap();
        assert!(
            rootdir.path().join("var/lib/docker").is_dir(),
            "no tmpfs /var ⇒ build-time mkdir is correct"
        );
    }
}
