-- whichllm: find the best local LLM that runs on your hardware.
--
-- Ported from the devbox global profile (Tier 3) as the first pip-based
-- pod package (ADR-0017 dependency fetch, issue #13). The dependency
-- closure resolves from upstream's uv.lock (the Python analog of a
-- package-lock.json): whichllm's own PyPI wheel plus its runtime deps,
-- fetched as hash-verified wheel downloads. dbgpu is sdist-only and is
-- skipped by the resolver — whichllm wraps its import in try/except and
-- degrades to static GPU data (the same fallback as pip installs without
-- dbgpu). The build unzips the wheels into site-packages and stages the
-- console script; the wrapper hands site-packages to the pod's python3
-- via PYTHONPATH.

return {
    default = snap {
        name = "whichllm",
        version = "0.5.16",
        summary = "Find the best local LLM that runs on your hardware",
        description = [[
            whichllm inspects your GPU, VRAM, memory, and platform, then
            ranks locally-runnable LLMs (GGUF quantizations included)
            against that hardware. Built from the upstream source
            tarball; the pip dependency closure is declared via
            deps.pip against upstream's uv.lock and fetched as a
            content-hashed pod-store entry (ADR-0017).
        ]],
        license = "MIT",
        grade = "stable",
        confinement = "strict",
        architectures = { "amd64" },

        source = {
            url = "https://github.com/Andyyyy64/whichllm/archive/refs/tags/v0.5.16.tar.gz",
            sha256 = "07545cf151960b98b8f309171a556953139348a52eb005117dbd1c302c85191d",
        },

        deps = {
            pip = { lock = "uv.lock" },
        },

        build = table.concat({
            "mkdir -p $STAGE/usr/lib/python3.12/site-packages $STAGE/usr/bin",
            -- whichllm is the uv workspace ROOT in its own uv.lock
            -- (source = editable), so the resolver skips it: install the
            -- package from the source tree (pure Python, src layout).
            "cp -r $SRC/src/whichllm $STAGE/usr/lib/python3.12/site-packages/",
            "for w in \"$SHUTTLE_DEPS_DIR\"/*.whl; do " ..
                "python3 -m zipfile -e \"$w\" \"$STAGE/usr/lib/python3.12/site-packages/\"; done",
            -- The wheel's console-script entry point (whichllm = "whichllm.cli:app"),
            -- generated by hand: the interpreter wrapper resolves python3
            -- from the pod and PYTHONPATH from the staged site-packages.
            "printf '#!/usr/bin/env python3\\nfrom whichllm.cli import app\\napp()\\n' > $STAGE/usr/bin/whichllm",
            "chmod +x $STAGE/usr/bin/whichllm",
        }, " && "),

        type = "source",
        requires = { "glibc" },

        apps = {
            whichllm = app {
                command = "usr/bin/whichllm",
                interpreter = "python3",
            },
        },
    },
}
