-- ninja: Small build system for high-speed builds
--
-- Source: https://github.com/ninja-build/ninja/archive/refs/tags/v1.12.1.tar.gz
return {
    default = snap {
        name = "ninja",
        version = "1.12.1",
        summary = "Small build system for high-speed builds",
        description = [[Ninja is a small build system with a focus on speed. It differs from
other build systems in two major ways: it is designed to have its input
files generated by a higher-level build system, and it is designed
to run builds as fast as possible.]],
        grade = "stable",
        confinement = "strict",
        architectures = { "amd64" },
        source = { url = "https://github.com/ninja-build/ninja/archive/refs/tags/v1.12.1.tar.gz" },
        build = "cmake -B build -DCMAKE_INSTALL_PREFIX=/usr && cmake --build build && DESTDIR=$STAGE cmake --install build",
    },
}
