-- libstdcpp: GNU Standard C++ Library v3
--
-- Source: https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.xz
-- Provides the shared library for C++ standard library support.
--
-- Repaired (issue #34): the standalone `../libstdc++-v3/configure` flow
-- silently disabled C++11 threads in this sandbox. Its gthreads feature
-- test (GLIBCXX_CHECK_GTHREADS) compiles `#include "gthr.h"` with
-- -I<top_srcdir>/libgcc -I<top_builddir>/libgcc, but `gthr.h` pulls in
-- "gthr-default.h" — a file only generated by libgcc's own build (a
-- symlink to the target's thread header, placed in libgcc's OWN build
-- dir) — and the sandbox toolchain (nix gcc) ships no gthr headers of its
-- own. With that input missing the test program failed to compile,
-- configure recorded "no gthreads" (_GLIBCXX_HAS_GTHREADS undefined),
-- `<mutex>` declared no std::mutex, and src/c++20/tzdb.cc died with
-- "'mutex' does not name a type" at its `mutex infos_mutex;` member.
-- The fix seeds the probed -I path with the exact artifact the canonical
-- flow relies on finding: a gthr-default.h symlink to the source tree's
-- posix thread header (the model libgcc's own configure selects for
-- x86_64-linux) — so the feature test compiles for real and threads are
-- detected on their merits.

return {
    default = snap {
        name = "libstdcpp",
        version = "14.2",
        summary = "GNU Standard C++ Library v3",
        description = [[
            libstdc++ is the GNU implementation of the C++ Standard
            Library. It provides the shared library (libstdc++.so) needed
            to run C++ applications. This package builds only the runtime
            library from the GCC source tree.
        ]],
        grade = "stable",
        confinement = "strict",
        -- amd64 only, like the rest of the pool that actually builds on
        -- this host: arm64/armhf would need a configured cross toolchain.
        architectures = { "amd64" },
        type = "source",
        -- libgcc is a runtime dependency: libstdc++.so.6 has
        -- DT_NEEDED libgcc_s.so.1 (unwinder personality symbols).
        requires = { "glibc", "libgcc" },
        source = {
            url = "https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.xz",
            sha256 = "a7b39bc69cbf9e25826c5a60ab26477001f7c08d85cec04bc0e29cabed6f3cc9",
        },
        build = table.concat({
            -- gthr seed: the gthreads feature test (GLIBCXX_CHECK_GTHREADS)
            -- compiles `#include "gthr.h"` with
            -- -I<top_srcdir>/libgcc -I<top_builddir>/libgcc, but
            -- "gthr-default.h" is generated only by libgcc's own build (a
            -- symlink to the target's thread header), and the sandbox
            -- toolchain (nix gcc) ships no gthr headers of its own. With
            -- that input missing the test program fails to compile and
            -- configure silently records "no gthreads"
            -- (_GLIBCXX_HAS_GTHREADS undefined), so <mutex> declares no
            -- std::mutex and src/c++20/tzdb.cc dies with "'mutex' does not
            -- name a type" at its `mutex infos_mutex;` member. Seed the
            -- file where the probe's quoted-include search looks FIRST —
            -- the directory of gthr.h itself, the source tree's libgcc/ —
            -- with a symlink to the posix thread header sitting next to
            -- it (the model libgcc's own configure selects for
            -- x86_64-linux), so the feature test compiles for real. (The
            -- top-level configure flow would drag in GMP/MPFR/MPC checks
            -- for a compiler we never build — the standalone configure is
            -- the right scope here.)
            "ln -s gthr-posix.h libgcc/gthr-default.h",
            "mkdir build",
            "cd build",
            "../libstdc++-v3/configure --prefix=/usr --disable-multilib --disable-libstdcxx-pch",
            "make -j$(nproc)",
            "make install DESTDIR=$STAGE",
            -- libtool drops .la metadata next to the libraries carrying
            -- absolute build-time paths (dependency_libs with
            -- -L/shuttle-build-prefix/...); nothing in the pool consumes
            -- libtool archives at runtime, so strip them from the payload
            -- rather than ship build-host paths.
            "find $STAGE -name '*.la' -type f -delete",
        }, " && "),

        -- Interim leak-scan escape (ADR-0018 Decision 3, issue #22), same
        -- rationale as git/htop/libsecret: the nix gcc wrapper bakes
        -- RUNPATH=/shuttle-build-prefix/usr/lib into the produced
        -- libstdc++.so. That path does not exist at runtime; silenced
        -- here, visibly logged by the leak scan, pending the RUNPATH
        -- repair (issue #22's portability follow-up).
        leaks_ok = { "/shuttle-build-prefix/usr/lib" },
    },
}
