-- hermes-agent: the self-improving AI agent (NousResearch/hermes-agent).
--
-- Ported from the devbox global profile (Tier 3, uv2nix upstream) as
-- the first FLOATING pod package: hermes ships multiple releases a day,
-- so deps = pip against upstream's uv.lock re-resolves on every sync
-- (still hash-verified; the last-known pin is kept for rollback —
-- ADR-0017 Decision 5). The source stays pinned to the release tag;
-- `pod update` moves it deliberately. The uv workspace root
-- (source = editable) is skipped by the resolver, so the build stages
-- the project's own code into site-packages alongside the fetched
-- wheels: the setuptools package dirs + the flat py-modules (the
-- upstream pyproject ships both). Upstream caps requires-python at
-- <3.14; the pod's python 3.12 satisfies it. Devbox parity note: the
-- flake scrubbed PYTHONPATH around the upstream venv for the same
-- pydantic_core ABI clash the app wrapper's SHUTTLE_PYTHONPATH handoff
-- solves here.

return {
    default = snap {
        name = "hermes-agent",
        version = "2026.8.31",
        summary = "The self-improving AI agent — skills from experience, runs anywhere",
        description = [[
            hermes-agent creates skills from experience, improves them
            during use, and runs anywhere (CLI, ACP adapter, gateway).
            Built from the upstream release tarball; the pip dependency
            closure is declared via deps.pip against upstream's uv.lock
            and fetched as a content-hashed pod-store entry (ADR-0017),
            re-resolved on every sync (floating).
        ]],
        license = "MIT",
        grade = "stable",
        confinement = "strict",
        architectures = { "amd64" },
        floating = true,

        source = {
            url = "https://github.com/NousResearch/hermes-agent/archive/refs/tags/v2026.8.31.tar.gz",
            sha256 = "78fb3ff707ec1d17044b875ecac8bef28aa39d44242824f6871ca40afe7bf217",
        },

        deps = {
            pip = { lock = "uv.lock" },
        },

        build = table.concat({
            "mkdir -p $STAGE/usr/lib/python3.12/site-packages $STAGE/usr/bin",
            -- hermes-agent is the uv workspace ROOT in its own uv.lock
            -- (source = editable), so the resolver skips it: install the
            -- project from the source tree (pure Python, flat layout —
            -- the setuptools packages.find dirs plus the py-modules).
            "cp -r $SRC/agent $SRC/tools $SRC/hermes_cli $SRC/gateway $SRC/tui_gateway $SRC/cron $SRC/acp_adapter $SRC/plugins $SRC/providers $STAGE/usr/lib/python3.12/site-packages/",
            "cd $SRC && cp run_agent.py registration_lifecycle.py model_tools.py toolsets.py batch_runner.py trajectory_compressor.py toolset_distributions.py cli.py hermes_bootstrap.py hermes_constants.py hermes_state.py hermes_state_common.py hermes_state_portability.py hermes_state_schema.py hermes_state_search.py hermes_time.py hermes_logging.py utils.py mcp_serve.py $STAGE/usr/lib/python3.12/site-packages/",
            "for w in \"$SHUTTLE_DEPS_DIR\"/*.whl; do " ..
                "python3 -m zipfile -e \"$w\" \"$STAGE/usr/lib/python3.12/site-packages/\"; done",
            -- The wheel console-script entry points ([project.scripts]),
            -- generated by hand: the interpreter wrapper resolves python3
            -- from the pod and PYTHONPATH from the staged site-packages.
            "printf '#!/usr/bin/env python3\\nfrom hermes_cli.main import main\\nmain()\\n' > $STAGE/usr/bin/hermes",
            "printf '#!/usr/bin/env python3\\nfrom run_agent import main\\nmain()\\n' > $STAGE/usr/bin/hermes-agent",
            "printf '#!/usr/bin/env python3\\nfrom acp_adapter.entry import main\\nmain()\\n' > $STAGE/usr/bin/hermes-acp",
            "chmod +x $STAGE/usr/bin/hermes $STAGE/usr/bin/hermes-agent $STAGE/usr/bin/hermes-acp",
        }, " && "),

        type = "source",
        requires = { "glibc" },

        apps = {
            hermes = app {
                command = "usr/bin/hermes",
                interpreter = "python3",
            },
            ["hermes-agent"] = app {
                command = "usr/bin/hermes-agent",
                interpreter = "python3",
            },
            ["hermes-acp"] = app {
                command = "usr/bin/hermes-acp",
                interpreter = "python3",
            },
        },
    },
}
