-- skillspector: security scanner for AI agent skills
-- (NVIDIA/SkillSpector) — detects vulnerabilities in Claude Code /
-- Cursor-style skills before you install them.
--
-- Ported from devbox-global's devbox.d/skillspector flake. The flake
-- fetchFromGitHub-pins tag v2.11.2 (= the flake's rev); this port pins
-- the same tag's tarball (sha256 be47a3c40ed8…, codeload-mirror
-- verified). The flake's SRI hash is a NAR-of-tree digest (fetchFromGitHub
-- semantics), not a tarball digest, so the cross-check is at the rev
-- level plus mirror consistency rather than hash equality.
--
-- License note: the flake's meta says MIT, but upstream's own
-- pyproject.toml and LICENSE declare Apache-2.0 — the SPDX here follows
-- upstream (the flake's meta.license is a metadata bug, not ported).
--
-- Dependency closure: deps.pip against the uv.lock shipped in the
-- tarball (581 KB, requires-python >=3.12,<3.15 — the pod's python 3.14
-- fits). The resolver fetches every registry, non-dev-only,
-- platform-matching wheel from the lock; `python = "3.14"` makes the
-- fetch validate every wheel's tags against the pod interpreter —
-- uv.lock records the LOCKING machine's wheel choice, and without the
-- check it silently ships cp312 wheels a 3.14 runtime cannot import
-- (found live: pydantic_core's compiled module, 2026-09-18). The flake's
-- one custom build — pywhatwgurl 0.1.1 via hatch-vcs with a pretend
-- version — is unnecessary here: 0.1.1 publishes a pure py3-none-any
-- wheel that the lock carries directly. yara-python is excluded
-- outright: its published wheels stop at cp313 (no cp314, no abi3), so
-- none can serve the pod's python; skillspector's analyzer loader
-- skips the missing static_yara module with a logged error and every
-- other analyzer runs. The flake had no such gap because nixpkgs
-- compiles yara-python from the sdist against its own interpreter.
--
-- Requires: glibc plus libstdcpp/libgcc — the closure carries C++ and
--           Rust wheels (uvloop, pydantic-core, orjson, cryptography)
--           that link the system C++/gcc runtime (PEP 600 whitelist).
-- build_deps: (none)

return {
    default = snap {
        name = "skillspector",
        version = "2.11.2",
        summary = "Security scanner for AI agent skills",
        description = [[
            SkillSpector scans AI agent skills (Claude Code, Cursor,
            and similar) for vulnerabilities, malicious patterns, and
            security risks before installation. It accepts git repos,
            URLs, zips, and local directories, runs static pattern
            checks plus optional LLM semantic analysis, and emits
            terminal, JSON, or Markdown reports with risk scoring.
            Built from the upstream release tarball; the pip dependency
            closure is declared via deps.pip against upstream's
            uv.lock and fetched as a content-hashed pod-store entry
            (ADR-0017).
        ]],
        license = "Apache-2.0",
        grade = "stable",
        confinement = "strict",
        architectures = { "amd64" },

        source = {
            url = "https://github.com/NVIDIA/SkillSpector/archive/refs/tags/v2.11.2.tar.gz",
            sha256 = "be47a3c40ed84ff3df768bf4fa3200b7cf69cda3f091e854e72ef8fb4b11281e",
        },

        deps = {
            pip = { lock = "uv.lock", python = "3.14",
                    exclude = { "yara-python", "backports-zstd" } },
        },

        build = table.concat({
            "mkdir -p $STAGE/usr/lib/python3.14/site-packages $STAGE/usr/bin",
            -- skillspector is the uv workspace ROOT in its own uv.lock
            -- (editable source), so the resolver skips it: install the
            -- package from the source tree (pure Python, src layout).
            "cp -r $SRC/src/skillspector $STAGE/usr/lib/python3.14/site-packages/",
            "for w in \"$SHUTTLE_DEPS_DIR\"/*.whl; do " ..
                "python3 -m zipfile -e \"$w\" \"$STAGE/usr/lib/python3.14/site-packages/\"; done",
            -- The wheel console-script entry point
            -- (skillspector = "skillspector.cli:app"), generated by
            -- hand: the interpreter wrapper resolves python3 from the
            -- pod and PYTHONPATH from the staged site-packages.
            "printf '#!/usr/bin/env python3\\nfrom skillspector.cli import app\\napp()\\n' > $STAGE/usr/bin/skillspector",
            "chmod +x $STAGE/usr/bin/skillspector",
            -- The source copy above carries no dist-info, so
            -- importlib.metadata.version("skillspector") (the CLI's
            -- --version path) raises PackageNotFoundError — found live
            -- on the daily pod 2026-09-18. Synthesize the minimal
            -- metadata the source copy lacks.
            "mkdir -p $STAGE/usr/lib/python3.14/site-packages/skillspector-2.11.2.dist-info",
            "printf '%s\\n' 'Metadata-Version: 2.1' 'Name: skillspector' 'Version: 2.11.2' > $STAGE/usr/lib/python3.14/site-packages/skillspector-2.11.2.dist-info/METADATA",
        }, " && "),

        type = "source",
        requires = { "glibc", "libstdcpp", "libgcc" },

        apps = {
            skillspector = app {
                command = "usr/bin/skillspector",
                interpreter = "python3",
            },
        },
    },
}
